package modelo;
// Generated mar 20, 2018 3:48:40 p.m. by Hibernate Tools 4.3.1



/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private int idRespuesta;
     private int idPregunta;
     private String correoUsuario;
     private String texto;

    public Respuesta() {
    }

    public Respuesta(int idRespuesta, int idPregunta, String correoUsuario, String texto) {
       this.idRespuesta = idRespuesta;
       this.idPregunta = idPregunta;
       this.correoUsuario = correoUsuario;
       this.texto = texto;
    }
   
    public int getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(int idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }




}


